// App, Workspace, Session & Agent State Manifest
//
// Generated by scripts/gen-state-manifest.mts — do not edit by hand.
// Regenerate with: pnpm --filter @moonshot-ai/agent-core-v2 gen:state-manifest
//
// Every state key registered into the App-scope IAppStateService, the
// Workspace-scope IWorkspaceStateService, the Session-scope
// ISessionStateService, or the Agent-scope IAgentStateService (see
// src/_base/state/stateRegistry.ts), collected statically from the
// `states.contributeState(...)` call sites and the replayable key chains — a
// `defineState(...).replayable(...)` key is contributed into the Agent-scope
// service by its owner service at construction, and
// carries a `// replayable · durable|transient · undoable? — folds: ...` line.
// Replayable values are excluded from snapshot()/inspect(). A key defined via
// defineState but never registered nor replayable does not appear here. Each entry shows the
// compile-time StateKey<T> value type fully expanded inline, so the manifest is
// self-contained (no imports, no helper declarations). A named type is marked
// at its expansion site with a `/* TypeName — source/file.ts */` comment; a
// `/* TypeName — recursive (...) */ unknown` marker stops a recursive expansion.
// Lib globals (Map/Set/Record/…) are referenced as-is. Generic instantiations
// expand structurally; classes render as their public instance shape. The
// defining source file heads each group.
//
// snapshot() returns JSON-safe deep copies of these values: Maps become plain
// objects (or [key, value] entry arrays when a key is not string/number), Sets
// become arrays, bigints become strings, functions are dropped, circular
// references become '(circular)', and class instances collapse to a '(ClassName)'
// marker — the wire shape of an entry is the JSON projection of the type here.
//
// Index (App: 0 keys · Workspace: 6 keys · Session: 9 keys · Agent: 73 keys)
//   App
//   Workspace
//     workspaceDirs.ephemeralDirs          src/workspace/workspaceDirs/workspaceDirsService.ts
//     workspaceDirs.fileDirs               src/workspace/workspaceDirs/workspaceDirsService.ts
//     workspaceInstructions.current        src/workspace/workspaceInstructions/workspaceInstructionsService.ts
//     workspaceSkillCatalog.contributions  src/features/skill/workspace/workspaceSkillCatalogService.ts
//     workspaceSkillCatalog.merged         src/features/skill/workspace/workspaceSkillCatalogService.ts
//     workspaceTrust.trusted               src/workspace/workspaceTrust/workspaceTrustService.ts
//   Session
//     sessionActivity.current            src/session/sessionActivity/sessionActivityService.ts
//     sessionActivity.folds              src/session/sessionActivity/sessionActivityService.ts
//     sessionLog.rootLevel               src/session/sessionLog/sessionLogService.ts
//     sessionMetadata.data               src/session/sessionMetadata/sessionMetadataService.ts
//     sessionSkillCatalog.contributions  src/features/skill/session/skillCatalogService.ts
//     sessionSkillCatalog.merged         src/features/skill/session/skillCatalogService.ts
//     sessionToolPolicy.state            src/session/sessionToolPolicy/sessionToolPolicyService.ts
//     workspaceContext.additionalDirs    src/session/workspaceContext/workspaceContextService.ts
//     workspaceContext.workDir           src/session/workspaceContext/workspaceContextService.ts
//   Agent
//     agentPlugin.sessionStartRefreshPending          src/agent/plugin/agentPluginService.ts
//     agentsMdReminder.cwd                            src/agent/agentsMdReminder/agentsMdReminderService.ts
//     agentsMdReminder.known                          src/agent/agentsMdReminder/agentsMdReminderService.ts
//     agentsMdReminder.seeded                         src/agent/agentsMdReminder/agentsMdReminderService.ts
//     contextMemory                                   src/agent/contextMemory/contextOps.ts
//     contextProjector.lastRepairSignature            src/agent/contextProjector/contextProjectorService.ts
//     externalHooks.stopHookContinuationUsed          src/features/externalHooks/agent/agentExternalHooksService.ts
//     fileHistory                                     src/features/fileHistory/fileHistoryOps.ts
//     fullCompaction                                  src/agent/fullCompaction/compactionOps.ts
//     fullCompaction.activeTurnId                     src/agent/fullCompaction/fullCompactionService.ts
//     fullCompaction.compactionCountInTurn            src/agent/fullCompaction/fullCompactionService.ts
//     fullCompaction.consecutiveOverflowCompactions   src/agent/fullCompaction/fullCompactionService.ts
//     fullCompaction.lastCompactedTokenCount          src/agent/fullCompaction/fullCompactionService.ts
//     fullCompaction.observedMaxContextTokensByModel  src/agent/fullCompaction/fullCompactionService.ts
//     fullCompaction.wireRanges                       src/agent/fullCompaction/compactionOps.ts
//     interruptionReminder                            src/agent/interruptionReminder/interruptionReminderOps.ts
//     llm.requestTrace                                src/agent/llmRequester/llmRequestOps.ts
//     llmRequester.emittedThinkingEffortWarnings      src/agent/llmRequester/llmRequesterService.ts
//     llmRequester.lastConfigLogSignature             src/agent/llmRequester/llmRequesterService.ts
//     llmRequester.mediaDegradedTurns                 src/agent/llmRequester/llmRequesterService.ts
//     llmRequester.mediaStrippedTurns                 src/agent/llmRequester/llmRequesterService.ts
//     llmRequester.turnConfigs                        src/agent/llmRequester/llmRequesterService.ts
//     loop.disposing                                  src/agent/loop/loopService.ts
//     loop.lastRequestTraceId                         src/agent/loop/loopService.ts
//     mcp.discovery                                   src/agent/mcp/mcpDiscoveryOps.ts
//     mcp.discoveryWritesReady                        src/agent/mcp/mcpService.ts
//     mcp.mcpToolsByServer                            src/agent/mcp/mcpService.ts
//     media.budgetDropped                             src/agent/media/mediaResolverService.ts
//     media.registeredKey                             src/agent/media/mediaToolsRegistrar.ts
//     media.resolved                                  src/agent/media/mediaResolverService.ts
//     permissionMode                                  src/agent/permissionMode/permissionModeOps.ts
//     permissionMode.configured                       src/agent/permissionMode/permissionModeOps.ts
//     permissionMode.lastMode                         src/agent/permissionMode/injection/permissionModeInjection.ts
//     permissionRules                                 src/agent/permissionRules/permissionRulesOps.ts
//     plan                                            src/features/plan/planOps.ts
//     plan.wasActive                                  src/features/plan/injection/planModeInjection.ts
//     pluginSessionStartSnapshot                      src/agent/plugin/agentPluginOps.ts
//     profile                                         src/agent/profile/profileOps.ts
//     profile.activeToolNamesOverlay                  src/agent/profile/profileService.ts
//     profile.activeTools                             src/agent/profile/profileOps.ts
//     profile.agentsMdWarning                         src/agent/profile/profileService.ts
//     profile.emittedPluginBudgetWarnings             src/agent/profile/profileService.ts
//     profile.emittedThinkingEffortWarnings           src/agent/profile/profileService.ts
//     profile.emittedToolPatternWarnings              src/agent/profile/profileService.ts
//     runtime.binding                                 src/agent/runtimeBinding/runtimeBindingService.ts
//     runtimeBinding                                  src/agent/runtimeBinding/runtimeBindingOps.ts
//     shellCommand.tasks                              src/agent/shellCommand/shellCommandService.ts
//     swarm                                           src/features/swarm/swarmOps.ts
//     task                                            src/agent/task/taskOps.ts
//     task.activeTaskReminderPending                  src/agent/task/taskService.ts
//     task.deliveredNotificationKeys                  src/agent/task/taskService.ts
//     task.ghosts                                     src/agent/task/taskService.ts
//     task.notificationDelivery                       src/agent/task/taskService.ts
//     task.scheduledNotificationKeys                  src/agent/task/taskService.ts
//     toolDedupe.activeStep                           src/agent/toolDedupe/toolDedupeService.ts
//     toolDedupe.activeTurnId                         src/agent/toolDedupe/toolDedupeService.ts
//     toolDedupe.callKeyByCallId                      src/agent/toolDedupe/toolDedupeService.ts
//     toolDedupe.consecutiveCount                     src/agent/toolDedupe/toolDedupeService.ts
//     toolDedupe.consecutiveKey                       src/agent/toolDedupe/toolDedupeService.ts
//     toolDedupe.handoffPhase                         src/agent/toolDedupe/toolDedupeService.ts
//     toolDedupe.originalCallIndex                    src/agent/toolDedupe/toolDedupeService.ts
//     toolDedupe.stepCalls                            src/agent/toolDedupe/toolDedupeService.ts
//     toolDedupe.syntheticCallIds                     src/agent/toolDedupe/toolDedupeService.ts
//     toolDedupe.turnCallRecords                      src/agent/toolDedupe/toolDedupeService.ts
//     toolDedupe.turnRepeatCount                      src/agent/toolDedupe/toolDedupeService.ts
//     toolExecutor.dupTypeTurnId                      src/agent/toolExecutor/toolExecutorService.ts
//     toolExecutor.toolCallDupTypes                   src/agent/toolExecutor/toolExecutorService.ts
//     toolSelect.pendingLoaded                        src/agent/toolSelect/toolSelectService.ts
//     tower                                           src/features/tower/towerOps.ts
//     tower.base                                      src/features/tower/towerOps.ts
//     tower.owner                                     src/features/tower/towerOps.ts
//     turn                                            src/agent/loop/turnOps.ts
//     userTool                                        src/agent/userTool/userToolOps.ts

/** App-scope keys registered into IAppStateService. */
export interface AppStateSnapshot {
}

export type AppStateKey = keyof AppStateSnapshot;

/** Workspace-scope keys registered into IWorkspaceStateService. */
export interface WorkspaceStateSnapshot {
  // src/features/skill/workspace/workspaceSkillCatalogService.ts
  'workspaceSkillCatalog.contributions': Map<string, {
    readonly c: /* SkillContribution — packages/agent-core-v2/src/features/skill/catalog/skillSource.ts */ {
      readonly skills: readonly /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name: string;
        readonly description: string;
        readonly path: string;
        readonly dir: string;
        readonly content: string;
        readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
          readonly name?: string;
          readonly description?: string;
          readonly type?: string;
          readonly whenToUse?: string;
          readonly disableModelInvocation?: boolean;
          readonly isSubSkill?: boolean;
          readonly safe?: boolean;
          readonly arguments?: string | readonly unknown[];
          [key: string]: unknown;
        };
        readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
        readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
          readonly id: string;
          readonly instructions?: string;
        };
        readonly mermaid?: string;
        readonly d2?: string;
        readonly productSpecific?: boolean;
        readonly experimentalFlag?: string;
      }[];
      readonly skipped?: readonly /* SkippedSkill — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly path: string;
        readonly type: string;
        readonly reason: string;
      }[];
      readonly scannedRoots?: readonly string[];
    };
    readonly priority: number;
  }>;
  'workspaceSkillCatalog.merged': /* InMemorySkillCatalog — packages/agent-core-v2/src/features/skill/catalog/registry.ts */ {
    registerBuiltinSkill: (skill: /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }) => void;
    register: (skill: /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }, options?: {
      readonly replace?: boolean;
    }) => void;
    recordSkipped: (skills: readonly /* SkippedSkill — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly path: string;
      readonly type: string;
      readonly reason: string;
    }[]) => void;
    addRoots: (roots: readonly string[]) => void;
    getSkill: (name: string) => /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    } | undefined;
    getPluginSkill: (pluginId: string, name: string) => /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    } | undefined;
    renderSkillPrompt: (skill: /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }, rawArgs: string, context?: {
      readonly sessionId?: string;
    }) => string;
    listSkills: () => readonly /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }[];
    listInvocableSkills: () => readonly /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }[];
    getSkillRoots: () => readonly string[];
    getSkippedByPolicy: () => readonly /* SkippedSkill — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly path: string;
      readonly type: string;
      readonly reason: string;
    }[];
    getKimiSkillsDescription: () => string;
    getModelSkillListing: () => string;
  };
  // src/workspace/workspaceDirs/workspaceDirsService.ts
  'workspaceDirs.ephemeralDirs': readonly string[];
  'workspaceDirs.fileDirs': readonly string[];
  // src/workspace/workspaceInstructions/workspaceInstructionsService.ts
  'workspaceInstructions.current': /* WorkspaceInstructionsSnapshot — packages/agent-core-v2/src/workspace/workspaceInstructions/workspaceInstructions.ts */ {
    readonly agentsMd: string | undefined;
    readonly agentsMdWarning: string | undefined;
    readonly agentsMdPaths: readonly string[] | undefined;
  };
  // src/workspace/workspaceTrust/workspaceTrustService.ts
  'workspaceTrust.trusted': boolean;
}

export type WorkspaceStateKey = keyof WorkspaceStateSnapshot;

/** Session-scope keys registered into ISessionStateService. */
export interface SessionStateSnapshot {
  // src/features/skill/session/skillCatalogService.ts
  'sessionSkillCatalog.contributions': Map<string, {
    readonly c: /* SkillContribution — packages/agent-core-v2/src/features/skill/catalog/skillSource.ts */ {
      readonly skills: readonly /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name: string;
        readonly description: string;
        readonly path: string;
        readonly dir: string;
        readonly content: string;
        readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
          readonly name?: string;
          readonly description?: string;
          readonly type?: string;
          readonly whenToUse?: string;
          readonly disableModelInvocation?: boolean;
          readonly isSubSkill?: boolean;
          readonly safe?: boolean;
          readonly arguments?: string | readonly unknown[];
          [key: string]: unknown;
        };
        readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
        readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
          readonly id: string;
          readonly instructions?: string;
        };
        readonly mermaid?: string;
        readonly d2?: string;
        readonly productSpecific?: boolean;
        readonly experimentalFlag?: string;
      }[];
      readonly skipped?: readonly /* SkippedSkill — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly path: string;
        readonly type: string;
        readonly reason: string;
      }[];
      readonly scannedRoots?: readonly string[];
    };
    readonly priority: number;
  }>;
  'sessionSkillCatalog.merged': /* InMemorySkillCatalog — packages/agent-core-v2/src/features/skill/catalog/registry.ts */ {
    registerBuiltinSkill: (skill: /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }) => void;
    register: (skill: /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }, options?: {
      readonly replace?: boolean;
    }) => void;
    recordSkipped: (skills: readonly /* SkippedSkill — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly path: string;
      readonly type: string;
      readonly reason: string;
    }[]) => void;
    addRoots: (roots: readonly string[]) => void;
    getSkill: (name: string) => /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    } | undefined;
    getPluginSkill: (pluginId: string, name: string) => /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    } | undefined;
    renderSkillPrompt: (skill: /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }, rawArgs: string, context?: {
      readonly sessionId?: string;
    }) => string;
    listSkills: () => readonly /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }[];
    listInvocableSkills: () => readonly /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }[];
    getSkillRoots: () => readonly string[];
    getSkippedByPolicy: () => readonly /* SkippedSkill — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly path: string;
      readonly type: string;
      readonly reason: string;
    }[];
    getKimiSkillsDescription: () => string;
    getModelSkillListing: () => string;
  };
  // src/session/sessionActivity/sessionActivityService.ts
  'sessionActivity.current': /* SessionActivityState — packages/agent-core-v2/src/session/sessionActivity/sessionActivity.ts */ {
    readonly busy: boolean;
    readonly mainTurnActive: boolean;
    readonly pendingInteraction: /* SessionPendingInteraction — packages/agent-core-v2/src/session/sessionActivity/sessionActivity.ts */ 'none' | 'approval' | 'question';
    readonly lastTurnReason?: 'completed' | 'cancelled' | 'failed';
  };
  'sessionActivity.folds': Map<string, /* AgentWorkFold — packages/agent-core-v2/src/session/sessionActivity/sessionActivityService.ts */ {
    turnActive: boolean;
    background: ReadonlySet<string>;
    compacting: boolean;
    lastTurnReason?: 'completed' | 'cancelled' | 'failed';
  }>;
  // src/session/sessionLog/sessionLogService.ts
  'sessionLog.rootLevel': /* LogLevelState — packages/agent-core-v2/src/_base/log/logService.ts */ {
    level: /* LogLevel — packages/agent-core-v2/src/_base/log/log.ts */ 'info' | 'off' | 'error' | 'warn' | 'debug';
  };
  // src/session/sessionMetadata/sessionMetadataService.ts
  'sessionMetadata.data': /* SessionMeta — packages/agent-core-v2/src/session/sessionMetadata/sessionMetadata.ts */ {
    readonly id: string;
    readonly version?: number;
    readonly title?: string;
    readonly titleKind?: 'replaceable' | 'generated' | 'custom';
    readonly lastPrompt?: string;
    readonly createdAt: number;
    readonly updatedAt: number;
    readonly archived: boolean;
    readonly archivedAt?: number;
    readonly cwd?: string;
    readonly forkedFrom?: string;
    readonly agents?: Readonly<Record<string, /* AgentMeta — packages/agent-core-v2/src/session/sessionMetadata/sessionMetadata.ts */ {
      readonly homedir?: string;
      readonly type?: 'main' | 'sub' | 'independent';
      readonly parentAgentId?: string | null;
      readonly forkedFrom?: string;
      readonly labels?: Readonly<Record<string, string>>;
      readonly swarmItem?: string;
    }>>;
    readonly custom?: Record<string, unknown>;
    readonly lastTurnReason?: 'completed' | 'cancelled' | 'failed';
  } | undefined;
  // src/session/sessionToolPolicy/sessionToolPolicyService.ts
  'sessionToolPolicy.state': /* SessionToolPolicyState — packages/agent-core-v2/src/session/sessionToolPolicy/sessionToolPolicyService.ts */ {
    readonly disabledTools: readonly string[];
  };
  // src/session/workspaceContext/workspaceContextService.ts
  'workspaceContext.additionalDirs': string[];
  'workspaceContext.workDir': string;
}

export type SessionStateKey = keyof SessionStateSnapshot;

/** Agent-scope keys registered into IAgentStateService. */
export interface AgentStateSnapshot {
  // src/agent/agentsMdReminder/agentsMdReminderService.ts
  'agentsMdReminder.cwd': string | undefined;
  'agentsMdReminder.known': Set<string>;
  'agentsMdReminder.seeded': boolean;
  // src/agent/contextMemory/contextOps.ts
  // replayable · durable · undoable — folds: ContextAppendMessage, ContextAppendLoopEvent, ContextClear, ContextApplyCompaction
  'contextMemory': (/* ContextMessage — packages/agent-core-v2/src/agent/contextMemory/types.ts */ /* Message — packages/agent-core-v2/src/llm-adapter/contract/message.ts */ {
    readonly role: /* Role — packages/agent-core-v2/src/human/llm/message.ts */ 'user' | 'system' | 'assistant' | 'tool';
    readonly name?: string;
    readonly content: (/* ContentPart — packages/agent-core-v2/src/human/llm/message.ts */ /* TextPart — packages/agent-core-v2/src/human/llm/message.ts */ {
      type: 'text';
      text: string;
    } | /* ThinkPart — packages/agent-core-v2/src/human/llm/message.ts */ {
      type: 'think';
      think: string;
      encrypted?: string;
      detailsIndex?: number;
      hidden?: boolean;
    } | /* ImageURLPart — packages/agent-core-v2/src/human/llm/message.ts */ {
      type: 'image_url';
      imageUrl: {
        url: string;
        id?: string;
        name?: string;
      };
    } | /* AudioURLPart — packages/agent-core-v2/src/human/llm/message.ts */ {
      type: 'audio_url';
      audioUrl: {
        url: string;
        id?: string;
      };
    } | /* VideoURLPart — packages/agent-core-v2/src/human/llm/message.ts */ {
      type: 'video_url';
      videoUrl: {
        url: string;
        id?: string;
        name?: string;
      };
    })[];
    readonly toolCalls: /* ToolCall — packages/agent-core-v2/src/human/llm/message.ts */ {
      type: 'function';
      id: string;
      name: string;
      arguments: string | null;
      extras?: Record<string, unknown>;
      rawId?: string;
      _streamIndex?: string | number;
    }[];
    readonly toolCallId?: string;
    readonly partial?: boolean;
    readonly tools?: readonly /* ToolDescription — packages/agent-core-v2/src/human/llm/message.ts */ {
      name: string;
      description: string;
      parameters: Record<string, unknown>;
      deferred?: true;
    }[];
  } & {
    readonly id?: string;
    readonly providerMessageId?: string;
    readonly origin?: /* UserPromptOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'user';
      readonly skillActivations?: readonly /* BundledSkillActivation — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly activationId: string;
        readonly skillName: string;
        readonly skillArgs?: string;
        readonly skillType?: string;
        readonly skillPath?: string;
        readonly skillSource?: 'project' | 'user' | 'extra' | 'builtin';
      }[];
      readonly attachments?: readonly /* PromptFileAttachment — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly name: string;
        readonly mediaType: string;
        readonly size: number;
        readonly path: string;
      }[];
    } | /* SkillActivationOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'skill_activation';
      readonly activationId: string;
      readonly skillName: string;
      readonly skillArgs?: string;
      readonly trigger: 'user-slash' | 'model-tool' | 'nested-skill';
      readonly skillType?: string;
      readonly skillPath?: string;
      readonly skillSource?: 'project' | 'user' | 'extra' | 'builtin';
      readonly attachments?: readonly /* PromptFileAttachment — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly name: string;
        readonly mediaType: string;
        readonly size: number;
        readonly path: string;
      }[];
    } | /* PluginCommandOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'plugin_command';
      readonly activationId: string;
      readonly pluginId: string;
      readonly commandName: string;
      readonly commandArgs?: string;
      readonly trigger: 'user-slash';
    } | /* InjectionOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'injection';
      readonly variant: string;
      readonly ownerPromptId?: string;
      readonly disclosure?: unknown;
    } | /* ShellCommandOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'shell_command';
      readonly phase: 'input' | 'output';
      readonly isError?: boolean;
    } | /* CompactionSummaryOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'compaction_summary';
    } | /* SystemTriggerOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'system_trigger';
      readonly name: string;
    } | /* TaskOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'task';
      readonly taskId: string;
      readonly status: /* AgentTaskStatus — packages/agent-core-v2/src/agent/task/types.ts */ 'completed' | 'failed' | 'running' | 'timed_out' | 'killed' | 'lost';
      readonly notificationId: string;
    } | /* CronJobOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'cron_job';
      readonly jobId: string;
      readonly cron: string;
      readonly recurring: boolean;
      readonly coalescedCount: number;
      readonly stale: boolean;
    } | /* CronMissedOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'cron_missed';
      readonly count: number;
    } | /* HookResultOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'hook_result';
      readonly event: string;
      readonly blocked?: boolean;
    } | /* RetryOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'retry';
      readonly trigger?: string;
    };
    readonly isError?: boolean;
    toolCallDisplays?: Record<string, /* ToolInputDisplay — packages/agent-core-v2/src/tool/toolInputDisplay.ts */ {
      kind: 'command';
      command: string;
      cwd?: string;
      description?: string;
      language?: 'bash';
    } | {
      kind: 'file_io';
      operation: 'read' | 'write' | 'edit' | 'glob' | 'grep';
      path: string;
      detail?: string;
      content?: string;
      before?: string;
      after?: string;
    } | {
      kind: 'diff';
      path: string;
      before: string;
      after: string;
      hunks?: number;
    } | {
      kind: 'search';
      query: string;
      scope?: string;
    } | {
      kind: 'url_fetch';
      url: string;
      method?: string;
    } | {
      kind: 'agent_call';
      agent_name: string;
      prompt: string;
      background?: boolean;
    } | {
      kind: 'skill_call';
      skill_name: string;
      args?: string;
    } | {
      kind: 'todo_list';
      items: {
        title: string;
        status: string;
      }[];
    } | {
      kind: 'task';
      task_id: string;
      status: string;
      description: string;
      task_kind?: string;
    } | {
      kind: 'task_stop';
      task_id: string;
      task_description: string;
    } | {
      kind: 'plan_review';
      plan: string;
      path?: string;
      options?: readonly {
        label: string;
        description: string;
      }[];
    } | {
      kind: 'goal_start';
      objective: string;
      completionCriterion?: string;
      mode: 'manual' | 'yolo';
    } | {
      kind: 'generic';
      summary: string;
      detail?: unknown;
    }>;
    readonly note?: string;
  })[];
  // src/agent/contextProjector/contextProjectorService.ts
  'contextProjector.lastRepairSignature': string | null;
  // src/agent/fullCompaction/compactionOps.ts
  // replayable · durable — folds: FullCompactionBegin, FullCompactionCancel, FullCompactionComplete
  'fullCompaction': /* CompactionState — packages/agent-core-v2/src/agent/fullCompaction/compactionOps.ts */ {
    readonly phase: /* CompactionPhase — packages/agent-core-v2/src/agent/fullCompaction/compactionOps.ts */ 'completed' | 'cancelled' | 'running' | 'idle';
  };
  // replayable · durable — folds: ContextApplyCompaction, ContextClear
  'fullCompaction.wireRanges': readonly /* WireLineRange — packages/agent-core-v2/src/wire/record.ts */ {
    readonly start: number;
    readonly end: number;
  }[];
  // src/agent/fullCompaction/fullCompactionService.ts
  'fullCompaction.activeTurnId': number | undefined;
  'fullCompaction.compactionCountInTurn': number;
  'fullCompaction.consecutiveOverflowCompactions': number;
  'fullCompaction.lastCompactedTokenCount': number | null;
  'fullCompaction.observedMaxContextTokensByModel': Map<string, number>;
  // src/agent/interruptionReminder/interruptionReminderOps.ts
  // replayable · durable — folds: InterruptionReminderRecorded
  'interruptionReminder': null;
  // src/agent/llmRequester/llmRequestOps.ts
  // replayable · durable — folds: LlmToolsSnapshot, LlmRequest
  'llm.requestTrace': /* LlmRequestTraceState — packages/agent-core-v2/src/agent/llmRequester/llmRequestOps.ts */ {
    readonly seenToolsHashes: readonly string[];
  };
  // src/agent/llmRequester/llmRequesterService.ts
  'llmRequester.emittedThinkingEffortWarnings': Set<string>;
  'llmRequester.lastConfigLogSignature': string | undefined;
  'llmRequester.mediaDegradedTurns': Set<number>;
  'llmRequester.mediaStrippedTurns': Map<number, /* MediaStripSnapshot — packages/agent-core-v2/src/agent/contextProjector/contextProjector.ts */ {
    readonly "__@mediaStripSnapshotBrand": undefined;
  }>;
  'llmRequester.turnConfigs': Map<number, /* TurnRequestConfig — packages/agent-core-v2/src/agent/llmRequester/llmRequesterService.ts */ {
    readonly resolved: /* ProfileModelContext — packages/agent-core-v2/src/agent/profile/profile.ts */ {
      readonly modelAlias: string;
      readonly modelCapabilities: /* ModelCapability — packages/agent-core-v2/src/llm-adapter/contract/capability.ts */ {
        readonly image_in: boolean;
        readonly video_in: boolean;
        readonly audio_in: boolean;
        readonly thinking: boolean;
        readonly tool_use: boolean;
        readonly max_context_tokens: number;
        readonly max_input_tokens?: number;
        readonly dynamically_loaded_tools?: boolean;
      };
      readonly maxOutputSize: number | undefined;
      readonly alwaysThinking: boolean | undefined;
      readonly thinkingLevel: /* ThinkingEffort — packages/agent-core-v2/src/human/llm/thinking.ts */ 'off' | 'on' | (string & {});
      readonly compactionThinkingLevel: 'off' | 'on' | (string & {}) | undefined;
      readonly compactionMaxOutputSize: number | undefined;
      readonly reservedContextSize: number | undefined;
      readonly compactionTriggerRatio: number | undefined;
      readonly compactionMaxAttempts: number | undefined;
    };
    readonly params: /* ModelRequestParams — packages/agent-core-v2/src/llm-adapter/model/model-requester.ts */ {
      readonly cacheKey?: string;
      readonly sampling?: /* SamplingOptions — packages/agent-core-v2/src/llm-adapter/model/model-requester.ts */ {
        readonly temperature?: number;
        readonly topP?: number;
      };
      readonly thinkingEffort?: 'off' | 'on' | (string & {});
      readonly thinkingKeep?: string;
      readonly maxCompletionTokens?: number;
      readonly usedContextTokens?: number;
      readonly maxContextTokens?: number;
      readonly onTraceId?: (traceId: string | null) => void;
    };
    readonly systemPrompt: string;
  }>;
  // src/agent/loop/loopService.ts
  'loop.disposing': boolean;
  'loop.lastRequestTraceId': string | undefined;
  // src/agent/loop/turnOps.ts
  // replayable · durable — folds: ContextAppendLoopEvent, TurnPrompt, TurnSteer, ContextUndo, ContextApplyCompaction, ContextClear, TurnCancel, TurnEnded
  'turn': /* TurnModelState — packages/agent-core-v2/src/agent/loop/turnOps.ts */ {
    readonly nextTurnId: number;
    readonly cancelledTurnIds: readonly number[];
    readonly anchorTurnIds: readonly number[];
    readonly lastEnded?: {
      readonly turnId: number;
      readonly reason: 'completed' | 'cancelled' | 'failed' | 'blocked';
      readonly durationMs?: number;
    };
  };
  // src/agent/mcp/mcpDiscoveryOps.ts
  // replayable · durable — folds: McpToolsDiscovered
  'mcp.discovery': /* McpDiscoveryState — packages/agent-core-v2/src/agent/mcp/mcpDiscoveryOps.ts */ {
    readonly seen: readonly string[];
  };
  // src/agent/mcp/mcpService.ts
  'mcp.discoveryWritesReady': boolean;
  'mcp.mcpToolsByServer': Map<string, string[]>;
  // src/agent/media/mediaResolverService.ts
  'media.budgetDropped': Set<string>;
  'media.resolved': Map<string, /* ContentPart — packages/agent-core-v2/src/human/llm/message.ts */ /* TextPart — packages/agent-core-v2/src/human/llm/message.ts */ {
    type: 'text';
    text: string;
  } | /* ThinkPart — packages/agent-core-v2/src/human/llm/message.ts */ {
    type: 'think';
    think: string;
    encrypted?: string;
    detailsIndex?: number;
    hidden?: boolean;
  } | /* ImageURLPart — packages/agent-core-v2/src/human/llm/message.ts */ {
    type: 'image_url';
    imageUrl: {
      url: string;
      id?: string;
      name?: string;
    };
  } | /* AudioURLPart — packages/agent-core-v2/src/human/llm/message.ts */ {
    type: 'audio_url';
    audioUrl: {
      url: string;
      id?: string;
    };
  } | /* VideoURLPart — packages/agent-core-v2/src/human/llm/message.ts */ {
    type: 'video_url';
    videoUrl: {
      url: string;
      id?: string;
      name?: string;
    };
  }>;
  // src/agent/media/mediaToolsRegistrar.ts
  'media.registeredKey': string | undefined;
  // src/agent/permissionMode/injection/permissionModeInjection.ts
  'permissionMode.lastMode': 'manual' | 'yolo' | 'auto' | undefined;
  // src/agent/permissionMode/permissionModeOps.ts
  // replayable · durable — folds: PermissionSetMode
  'permissionMode': /* PermissionMode — packages/agent-core-v2/src/agent/permissionPolicy/types.ts */ 'manual' | 'yolo' | 'auto';
  // replayable · durable — folds: PermissionSetMode
  'permissionMode.configured': boolean;
  // src/agent/permissionRules/permissionRulesOps.ts
  // replayable · durable — folds: PermissionRulesAdd, PermissionRecordApprovalResult
  'permissionRules': /* PermissionRulesModelState — packages/agent-core-v2/src/agent/permissionRules/permissionRulesOps.ts */ {
    readonly rules: readonly /* PermissionRule — packages/agent-core-v2/src/agent/permissionRules/permissionRules.ts */ {
      readonly decision: /* PermissionRuleDecision — packages/agent-core-v2/src/agent/permissionRules/permissionRules.ts */ 'allow' | 'deny' | 'ask';
      readonly scope: /* PermissionRuleScope — packages/agent-core-v2/src/agent/permissionRules/permissionRules.ts */ 'project' | 'user' | 'turn-override' | 'session-runtime';
      readonly pattern: string;
      readonly reason?: string;
    }[];
    readonly sessionApprovalRulePatterns: readonly string[];
  };
  // src/agent/plugin/agentPluginOps.ts
  // replayable · durable — folds: PluginSessionStartEvent
  'pluginSessionStartSnapshot': /* PluginSessionStartSnapshotState — packages/agent-core-v2/src/agent/plugin/agentPluginOps.ts */ {
    readonly initialized: boolean;
    readonly content?: string;
  };
  // src/agent/plugin/agentPluginService.ts
  'agentPlugin.sessionStartRefreshPending': boolean;
  // src/agent/profile/profileOps.ts
  // replayable · durable — folds: ProfileBind, ConfigUpdate
  'profile': /* ProfileModelState — packages/agent-core-v2/src/agent/profile/profileOps.ts */ {
    readonly modelAlias?: string;
    readonly profileName?: string;
    readonly thinkingLevel: string;
    readonly systemPrompt: string;
    readonly environmentDisclosure?: /* EnvironmentDisclosureSnapshot — packages/agent-core-v2/src/app/agentProfileCatalog/agentProfileCatalog.ts */ {
      readonly cwd: string;
    };
    readonly renderGeneration: number;
    readonly agentsMdPaths?: readonly string[];
    readonly disallowedTools?: readonly string[];
    readonly subagents?: readonly string[];
  };
  // replayable · durable — folds: ToolsSetActiveTools, ToolsResetActiveTools, ProfileBind
  'profile.activeTools': /* ActiveToolsState — packages/agent-core-v2/src/agent/profile/profileOps.ts */ readonly string[] | undefined;
  // src/agent/profile/profileService.ts
  'profile.activeToolNamesOverlay': readonly string[] | undefined;
  'profile.agentsMdWarning': string | undefined;
  'profile.emittedPluginBudgetWarnings': Set<string>;
  'profile.emittedThinkingEffortWarnings': Set<string>;
  'profile.emittedToolPatternWarnings': Set<string>;
  // src/agent/runtimeBinding/runtimeBindingOps.ts
  // replayable · durable — folds: RuntimeSetBinding
  'runtimeBinding': /* RuntimeBinding — packages/agent-core-v2/src/runtime/runtime.ts */ {
    readonly workspaceId: string;
    readonly runtimeId: string;
  } | undefined;
  // src/agent/runtimeBinding/runtimeBindingService.ts
  'runtime.binding': /* RuntimeBinding — packages/agent-core-v2/src/runtime/runtime.ts */ {
    readonly workspaceId: string;
    readonly runtimeId: string;
  };
  // src/agent/shellCommand/shellCommandService.ts
  'shellCommand.tasks': Map<string, string>;
  // src/agent/task/taskOps.ts
  // replayable · durable — folds: TaskStarted, TaskTerminated
  'task': /* TaskModelState — packages/agent-core-v2/src/agent/task/taskOps.ts */ Map<string, /* AgentTaskInfo — packages/agent-core-v2/src/agent/task/types.ts */ /* QuestionTaskInfo — packages/agent-core-v2/src/agent/tools/ask-user-question/question-background-task.ts */ {
    readonly kind: 'question';
    readonly questionCount: number;
    readonly toolCallId?: string;
    readonly taskId: string;
    readonly description: string;
    readonly status: /* AgentTaskStatus — packages/agent-core-v2/src/agent/task/types.ts */ 'completed' | 'failed' | 'running' | 'timed_out' | 'killed' | 'lost';
    readonly detached?: boolean;
    readonly startedAt: number;
    readonly endedAt: number | null;
    readonly stopReason?: string;
    readonly terminalNotificationSuppressed?: boolean;
    readonly resumeReminded?: boolean;
    readonly timeoutMs?: number;
  } | /* SubagentTaskInfo — packages/agent-core-v2/src/agent/tools/agent/subagent-task.ts */ {
    readonly kind: 'agent';
    readonly agentId?: string;
    readonly subagentType?: string;
    readonly parentToolCallId?: string;
    readonly model?: string;
    readonly thinkingEffort?: string;
    readonly stopCode?: string;
    readonly taskId: string;
    readonly description: string;
    readonly status: /* AgentTaskStatus — packages/agent-core-v2/src/agent/task/types.ts */ 'completed' | 'failed' | 'running' | 'timed_out' | 'killed' | 'lost';
    readonly detached?: boolean;
    readonly startedAt: number;
    readonly endedAt: number | null;
    readonly stopReason?: string;
    readonly terminalNotificationSuppressed?: boolean;
    readonly resumeReminded?: boolean;
    readonly timeoutMs?: number;
  } | /* ProcessTaskInfo — packages/agent-core-v2/src/agent/tools/os/bash/process-task.ts */ {
    readonly kind: 'process';
    readonly command: string;
    readonly pid: number;
    readonly exitCode: number | null;
    readonly parentToolCallId?: string;
    readonly taskId: string;
    readonly description: string;
    readonly status: /* AgentTaskStatus — packages/agent-core-v2/src/agent/task/types.ts */ 'completed' | 'failed' | 'running' | 'timed_out' | 'killed' | 'lost';
    readonly detached?: boolean;
    readonly startedAt: number;
    readonly endedAt: number | null;
    readonly stopReason?: string;
    readonly terminalNotificationSuppressed?: boolean;
    readonly resumeReminded?: boolean;
    readonly timeoutMs?: number;
  }>;
  // src/agent/task/taskService.ts
  'task.activeTaskReminderPending': boolean;
  'task.deliveredNotificationKeys': Set<string>;
  'task.ghosts': Map<string, /* AgentTaskInfo — packages/agent-core-v2/src/agent/task/types.ts */ /* QuestionTaskInfo — packages/agent-core-v2/src/agent/tools/ask-user-question/question-background-task.ts */ {
    readonly kind: 'question';
    readonly questionCount: number;
    readonly toolCallId?: string;
    readonly taskId: string;
    readonly description: string;
    readonly status: /* AgentTaskStatus — packages/agent-core-v2/src/agent/task/types.ts */ 'completed' | 'failed' | 'running' | 'timed_out' | 'killed' | 'lost';
    readonly detached?: boolean;
    readonly startedAt: number;
    readonly endedAt: number | null;
    readonly stopReason?: string;
    readonly terminalNotificationSuppressed?: boolean;
    readonly resumeReminded?: boolean;
    readonly timeoutMs?: number;
  } | /* SubagentTaskInfo — packages/agent-core-v2/src/agent/tools/agent/subagent-task.ts */ {
    readonly kind: 'agent';
    readonly agentId?: string;
    readonly subagentType?: string;
    readonly parentToolCallId?: string;
    readonly model?: string;
    readonly thinkingEffort?: string;
    readonly stopCode?: string;
    readonly taskId: string;
    readonly description: string;
    readonly status: /* AgentTaskStatus — packages/agent-core-v2/src/agent/task/types.ts */ 'completed' | 'failed' | 'running' | 'timed_out' | 'killed' | 'lost';
    readonly detached?: boolean;
    readonly startedAt: number;
    readonly endedAt: number | null;
    readonly stopReason?: string;
    readonly terminalNotificationSuppressed?: boolean;
    readonly resumeReminded?: boolean;
    readonly timeoutMs?: number;
  } | /* ProcessTaskInfo — packages/agent-core-v2/src/agent/tools/os/bash/process-task.ts */ {
    readonly kind: 'process';
    readonly command: string;
    readonly pid: number;
    readonly exitCode: number | null;
    readonly parentToolCallId?: string;
    readonly taskId: string;
    readonly description: string;
    readonly status: /* AgentTaskStatus — packages/agent-core-v2/src/agent/task/types.ts */ 'completed' | 'failed' | 'running' | 'timed_out' | 'killed' | 'lost';
    readonly detached?: boolean;
    readonly startedAt: number;
    readonly endedAt: number | null;
    readonly stopReason?: string;
    readonly terminalNotificationSuppressed?: boolean;
    readonly resumeReminded?: boolean;
    readonly timeoutMs?: number;
  }>;
  // replayable · durable · undoable — folds: ContextAppendMessage, TaskWaitDelivered
  'task.notificationDelivery': readonly string[];
  'task.scheduledNotificationKeys': Set<string>;
  // src/agent/toolDedupe/toolDedupeService.ts
  'toolDedupe.activeStep': number;
  'toolDedupe.activeTurnId': number | undefined;
  'toolDedupe.callKeyByCallId': Map<string, string>;
  'toolDedupe.consecutiveCount': number;
  'toolDedupe.consecutiveKey': string | null;
  'toolDedupe.handoffPhase': /* HandoffPhase — packages/agent-core-v2/src/agent/toolDedupe/toolDedupeService.ts */ 'idle' | 'active' | 'pending' | 'done';
  'toolDedupe.originalCallIndex': Map<string, number>;
  'toolDedupe.stepCalls': string[];
  'toolDedupe.syntheticCallIds': Set<string>;
  'toolDedupe.turnCallRecords': Map<string, /* TurnCallRecord — packages/agent-core-v2/src/agent/toolDedupe/toolDedupeService.ts */ {
    count: number;
    lastStep: number;
  }>;
  'toolDedupe.turnRepeatCount': number;
  // src/agent/toolExecutor/toolExecutorService.ts
  'toolExecutor.dupTypeTurnId': number | undefined;
  'toolExecutor.toolCallDupTypes': Map<string, /* ToolCallDupType — packages/agent-core-v2/src/agent/toolExecutor/toolExecutor.ts */ 'same_step' | 'cross_step'>;
  // src/agent/toolSelect/toolSelectService.ts
  'toolSelect.pendingLoaded': Set<string>;
  // src/agent/userTool/userToolOps.ts
  // replayable · durable — folds: ToolsRegisterUserTool, ToolsUnregisterUserTool
  'userTool': /* UserToolModelState — packages/agent-core-v2/src/agent/userTool/userToolOps.ts */ Map<string, /* UserToolRegistration — packages/agent-core-v2/src/agent/userTool/userTool.ts */ {
    readonly name: string;
    readonly description: string;
    readonly parameters: Record<string, unknown>;
    readonly disclosure?: 'deferred' | 'inline';
  }>;
  // src/features/externalHooks/agent/agentExternalHooksService.ts
  'externalHooks.stopHookContinuationUsed': boolean;
  // src/features/fileHistory/fileHistoryOps.ts
  // replayable · durable — folds: FileHistoryCheckpointed, FileHistoryTracked
  'fileHistory': /* FileHistoryState — packages/agent-core-v2/src/features/fileHistory/fileHistory.ts */ {
    readonly checkpoints: readonly /* FileHistoryCheckpointRecord — packages/agent-core-v2/src/features/fileHistory/fileHistory.ts */ {
      readonly turnId: number;
      readonly phase?: 'start' | 'end';
      readonly entries: Readonly<Record<string, /* FileBackupEntry — packages/agent-core-v2/src/features/fileHistory/fileHistory.ts */ {
        readonly key: string | null;
        readonly version: number;
        readonly contentHash?: string;
        readonly size?: number;
        readonly oversize?: boolean;
        readonly mtimeMs?: number;
      }>>;
    }[];
    readonly tracked: readonly string[];
  };
  // src/features/plan/injection/planModeInjection.ts
  'plan.wasActive': boolean;
  // src/features/plan/planOps.ts
  // replayable · durable · undoable — folds: PlanModeEnter, PlanModeCancel, PlanModeExit, PlanRevision
  'plan': /* PlanState — packages/agent-core-v2/src/features/plan/planOps.ts */ {
    readonly active: boolean;
    readonly id?: string;
    readonly revisionCount?: Readonly<Record<string, number>>;
  };
  // src/features/swarm/swarmOps.ts
  // replayable · durable — folds: SwarmModeEnter, SwarmModeExit
  'swarm': 'tool' | 'task' | 'manual' | null;
  // src/features/tower/towerOps.ts
  // replayable · durable — folds: TowerModeEnter, TowerModeExit
  'tower': boolean;
  // replayable · durable — folds: TowerModeEnter, TowerModeExit
  'tower.base': string | null;
  // replayable · durable — folds: TowerModeEnter, TowerModeExit
  'tower.owner': string | undefined;
}

export type AgentStateKey = keyof AgentStateSnapshot;
